package com.jbit.dao;

import com.jbit.entity.AppInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int insert(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int insertSelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    AppInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppInfo record);

    List<AppInfo> findlist(@Param("querySoftwareName") String querySoftwareName,
                           @Param("queryStatus") Long queryStatus,
                           @Param("queryCategoryLevel1") Long queryCategoryLevel1,
                           @Param("queryFlatformId") Long queryFlatformId,
                           @Param("queryCategoryLevel2") Long queryCategoryLevel2,
                           @Param("queryCategoryLevel3") Long queryCategoryLevel3);
}